name: Flutter Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Unit Tests Job
  # 単体テストジョブ
  unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        # コードをチェックアウト
        uses: actions/checkout@v3

      - name: Set up Flutter
        # Flutter環境をセットアップ
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      - name: Install Dependencies
        # 依存関係をインストール
        run: flutter pub get

      - name: Run Unit Tests with Coverage
        # 単体テストをカバレッジ付きで実行
        run: flutter test test/unit --coverage

      - name: Upload Test Coverage Report
        # テストカバレッジレポートをアップロード
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/lcov.info

  # Static Analysis Job
  # 静的解析ジョブ
  static_analysis:
    name: Run Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        # コードをチェックアウト
        uses: actions/checkout@v3

      - name: Set up Flutter
        # Flutter環境をセットアップ
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      - name: Run Flutter Analyze
        # Flutterの静的解析を実行
        run: flutter analyze

  # Widget Tests Job
  # ウィジェットテストジョブ
  widget_tests:
    name: Run Widget Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        # コードをチェックアウト
        uses: actions/checkout@v3

      - name: Set up Flutter
        # Flutter環境をセットアップ
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      - name: Install Dependencies
        # 依存関係をインストール
        run: flutter pub get

      - name: Run Widget Tests
        # ウィジェットテストを実行
        run: flutter test test/widget --coverage

      - name: Upload Widget Test Coverage Report
        # ウィジェットテストのカバレッジレポートをアップロード
        uses: actions/upload-artifact@v3
        with:
          name: widget-coverage-report
          path: coverage/lcov.info

  # Build iOS App Job
  # iOSアプリのビルドジョブ
  build_ios:
    name: Build iOS App (.ipa)
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        # コードをチェックアウト
        uses: actions/checkout@v3

      - name: Set up Flutter
        # Flutter環境をセットアップ
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      - name: Install Dependencies
        # 依存関係をインストール
        run: flutter pub get

      - name: Build iOS
        # iOSアプリをビルド
        run: flutter build ios --release --no-codesign

      - name: Export iOS IPA
        # iOSのIPAファイルをエクスポート
        run: |
          cd build/ios/iphoneos
          xcrun -sdk iphoneos PackageApplication -v Runner.app -o ${{ github.workspace }}/Runner.ipa

      - name: Upload iOS IPA as Artifact
        # iOS IPAファイルをアーティファクトとしてアップロード
        uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: Runner.ipa

  # Build Android App Job
  # Androidアプリのビルドジョブ
  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        # コードをチェックアウト
        uses: actions/checkout@v3

      - name: Set up Flutter
        # Flutter環境をセットアップ
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      - name: Install Dependencies
        # 依存関係をインストール
        run: flutter pub get

      - name: Build Android APK
        # Android APKをビルド
        run: flutter build apk --release

      - name: Upload Android APK as Artifact
        # Android APKファイルをアーティファクトとしてアップロード
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
